### ISSUE TITLE
GMP version mismatch

### ISSUE THREAD

**Issue by tjungND** [libntl/ntl#15]
When GMP 6.2 or 6.2.1 is installed, NTL cannot be installed due to this error. 

![image](https://user-images.githubusercontent.com/35898010/139099411-e873a891-af7b-4c30-aee6-7dccdba046a5.png)

I'm not sure if this is intended though (e.g., due to known issues of latest versions of GMP?).

**Comment by victorshoup** [comment]
This means you have something improperly configured: you are compiling with a gmp.h that is one version but linking against a gmp that is a different version. This can lead to undefined behavior if not fixed. It is not a problem with NTL or GMP -- it is a problem with the way your system is configured.

I suggest you set the environment variables CPATH and LD_LIBRARY_PATH explicitly. These should be set to /usr/local/include and  /usr/local/lib, respectively, if you've done a fresh install of GMP yourself. Sometimes Linux distros have some version of GMP pre-installed, and this is what can cause this problem.

**Comment by tjungND** [comment]
Thanks! As you guessed, the Ubuntu instance on the cloud has a pre-installed GMP (6.1.2) and that was causing the issue.
